// Project gallery data — one entry per folder in images/projects/<year>/<project>/
// `type` is the raw category from each project's desc.txt.txt ('home' | 'apartment' | 'commercial').
// 'home' and 'apartment' both render as the "Residential" badge; 'commercial' renders as "Commercial".
const PROJECTS = [
  {
    id: 'bc-cancer-society',
    title: 'BC Cancer Society',
    year: 2026,
    type: 'commercial',
    description: "Sub-contracted to find matching panels and apply a matching finish to 2 panels that needed to be installed beside existing millwork. The hardest part was getting the finish right!",
    folder: 'images/projects/2026/BC Cancer Society',
    images: ['IMG_2329.jpeg'],
  },
  {
    id: 'beatty',
    title: 'Beatty',
    year: 2026,
    type: 'apartment',
    description: "An apartment renovation in the downtown core. The client wanted all of the old carpeting torn out for modern flooring. We also painted the walls to a colour of their choosing. general repairs and handyman tasks were completed alongside the renovation.",
    folder: 'images/projects/2026/Beatty',
    images: ['IMG_1039.jpeg', 'IMG_1041.jpeg'],
  },
  {
    id: 'mcmyn',
    title: 'Mcmyn',
    year: 2026,
    type: 'apartment',
    description: "Remove existing flooring and install vinyl flooring",
    folder: 'images/projects/2026/Mcmyn',
    images: ['before.jpeg', 'after.jpeg'],
  },
  {
    id: 'pokey-okey',
    title: 'Pokey Okey',
    year: 2026,
    type: 'commercial',
    description: "2025-2026\n\nWe installed cabinets, wooden countertops, and millwork on this project, as well as mounted some signs.",
    folder: 'images/projects/2026/Pokey Okey',
    images: ['IMG_1111.jpeg', 'IMG_1166.jpeg', 'IMG_1169.jpeg'],
  },
  {
    id: 'west-55',
    title: 'West 55',
    year: 2025,
    type: 'home',
    description: "Basement remodel/kitchen addition\n\nClient wanted basement space to have an added kitchen and additional room",
    folder: 'images/projects/2025/West 55',
    images: ['IMG_4644.jpeg'],
  },
  {
    id: 'smith',
    title: 'Smith',
    year: 2024,
    type: 'home',
    description: "old shed -> comfy loft!",
    folder: 'images/projects/2024/Smith',
    images: ['Smith Ave.jpeg'],
  },
  {
    id: 'bayridge',
    title: 'Bayridge',
    year: 2023,
    type: 'home',
    description: "2018-2023\n\nCustom concrete home build\n10,000 sqft, Project management, general contracting.\n\nWe were the general contractors for this stunning build. Our client did not hold back on any details that he wanted and wanted the best of the best. Lots of custom details, clean edges and modern design made for a challenging, but rewarding project that left our client with exactly what he was looking for: A strong, concrete home, with a warm interior, modern lines and small details that make life better for their family.",
    folder: 'images/projects/2023/bayridge',
    images: [
      'IMG_0028.jpeg', 'IMG_1833.jpeg', 'IMG_1834.jpeg', 'IMG_1969.jpeg',
      'IMG_2259.jpeg', 'IMG_2648.jpeg', 'IMG_2649.jpeg', 'IMG_3006.jpeg',
      'IMG_3356.jpeg', 'IMG_5083.jpeg', 'IMG_5102.jpeg', 'IMG_5103.jpeg',
      'IMG_5105.jpeg', 'IMG_5106.jpeg', 'IMG_5114.jpeg', 'IMG_5116.jpeg',
      'IMG_5371.jpeg', 'IMG_5372.jpeg', 'IMG_5375.jpeg', 'IMG_9798.jpeg',
      'IMG_9908.jpeg',
    ],
  },
  {
    id: 'charland',
    title: 'Charland',
    year: 2023,
    type: 'apartment',
    description: "Some work for a close friend of ours. Custom shelving in the laundry closet for better organization, details added and painted walls for the bedroom and future nursing room and some shelving for dead space in their bathroom.",
    folder: 'images/projects/2023/Charland',
    images: ['before.jpeg', 'IMG_3105.jpeg', 'IMG_4392.jpeg', 'IMG_7095.jpeg', 'after.jpeg'],
  },
  {
    id: 'mathers',
    title: 'Mathers',
    year: 2014,
    type: 'home',
    description: "replace existing door\nenlarge opening/entrance",
    folder: 'images/projects/2014/Mathers',
    images: ['mathers_before.jpeg', 'Mathers_after.jpeg'],
  },
];
